name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle
      - name: Create Local Properties
        run: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "HOST_API=https://localhost" >> local.properties
          echo "HOST_WEB=https://localhost" >> local.properties
          echo "TOKEN_MAPBOX=otdkfdlfdklf" >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
      
